package org.gte.gtecore.data.lang;

import org.gte.gtecore.api.GTEValues;
import org.gte.gtecore.client.Tooltips;
import org.gte.gtecore.utils.ItemUtils;

import com.gregtechceu.gtceu.api.GTValues;

import static org.gte.gtecore.data.lang.LangHandler.addENCN;

final class ItemLang {

    static void init() {
        addENCN(GTEValues.REMOVING_ASH, "Removing ash...", "掏灰中...");
        addENCN(GTEValues.MAINTAINING, "Maintaining...", "维护中...");

        addENCN("item.gtceu.circuits", "Circuits", "电路");
        for (int i = 0; i < 15; i++) {
            addENCN("tag.item.gtceu.circuits." + GTValues.VN[i].toLowerCase(), GTValues.VN[i] + " Circuit", GTValues.VN[i] + "电路");
        }

        Tooltips.TOOL_TIPS_MAP.forEach((i, s) -> {
            for (int j = 0; j < s.length(); j++) {
                addENCN("gtecore.tooltip.item." + ItemUtils.getIdLocation(i).getPath() + "." + j, s.ens()[j], s.cns()[j]);
            }
        });

        addENCN("tagprefix.gloomslate", "Gloomslate %s Ore", "幽暗%s矿石");
        addENCN("tagprefix.sculk_stone", "Sculk %s Ore", "幽匿%s矿石");
        addENCN("tagprefix.ceres_stone", "Ceres %s Ore", "谷神星%s矿石");
        addENCN("tagprefix.contaminable_nanites", "Contaminable Nano Swarm", "污染的纳米蜂群");
        addENCN("tagprefix.enceladus_stone", "Enceladus %s Ore", "土卫二%s矿石");
        addENCN("tagprefix.ganymede_stone", "Ganymede %s Ore", "木卫三%s矿石");
        addENCN("tagprefix.glacio_stone", "Glacio %s Ore", "霜原石%s矿石");
        addENCN("tagprefix.io_stone", "Io %s Ore", "木卫一%s矿石");
        addENCN("tagprefix.mars_stone", "Mars %s Ore", "火星%s矿石");
        addENCN("tagprefix.mercury_stone", "Mercury %s Ore", "水星%s矿石");
        addENCN("tagprefix.milled", "Milled %s", "碾磨%s");
        addENCN("tagprefix.moon_stone", "Moon %s Ore", "月石%s矿石");
        addENCN("tagprefix.nanites", "%s Nano Swarm", "%s纳米蜂群");
        addENCN("tagprefix.pluto_stone", "Pluto %s Ore", "冥王星%s矿石");
        addENCN("tagprefix.titan_stone", "Titan %s Ore", "土卫六%s矿石");
        addENCN("tagprefix.venus_stone", "Venus %s Ore", "金星%s矿石");
        addENCN("tagprefix.curved_plate", "Curved %s Plate", "弯曲%s板");
        addENCN("tagprefix.motor_enclosure", "%s Motor Enclosure", "%s马达外壳");
        addENCN("tagprefix.pump_barrel", "%s Pump Barrel", "%s泵筒");
        addENCN("tagprefix.piston_housing", "%s Piston Housing", "%s活塞壳体");
        addENCN("tagprefix.emitter_base", "%s Emitter Base", "%s发射器基底");
        addENCN("tagprefix.sensor_casing", "%s Sensor Casing", "%s传感器外壳");
        addENCN("tagprefix.field_generator_casing", "%s Field Generator Casing", "%s力场发生器外壳");
        addENCN("tagprefix.rough_blank", "%s Rough Blank", "%s粗坯");
        addENCN("tagprefix.brick", "%s Brick", "%s砖");
        addENCN("tagprefix.flake", "%s Flake", "%s薄片");
        addENCN("tagprefix.catalyst", "%s Catalyst", "%s催化剂");
        addENCN("tagprefix.artificial_gem", "Artificial %s", "人造%s");
        addENCN("tagprefix.crystal_seed", "%s Crystal Seed", "%s晶种");
        addENCN("tagprefix.superconductor_base", "%s Superconductor Base", "%s超导粗胚");

        addENCN("gtecore.tooltip.artificial_gem", "Better than nature", "比自然的更好");
        addENCN("gtecore.tooltip.unknown", "Unknown", "未知");

        addENCN("item.gtceu.tool.hv_vajra", "%s Basic Vajra", "%s 基础金刚杵");
        addENCN("item.gtceu.tool.ev_vajra", "%s Advanced Vajra", "%s 高级金刚杵");
        addENCN("item.gtceu.tool.iv_vajra", "%s Ultimate Vajra", "%s 终极金刚杵");
        addENCN("gtecore.tooltip.item.kinetic_rotor.max", "Max Wind Speed: %s", "最大风力: %s");
        addENCN("gtecore.tooltip.item.kinetic_rotor.min", "Min Wind Speed: %s", "最小风力: %s");
        addENCN("gtecore.tooltip.item.virtual_item_provider", "Provide items for the machine's virtual circuit slot.", "为机器的虚拟电路槽提供物品");

        addENCN("gtecore.tooltip.item.really_max_battery", "Filling it up can allow you to complete GregTechCEu Modern", "填满它就能通关GregTechCEu Modern");
        addENCN("gtecore.tooltip.item.transcendent_max_battery", "Filling it up can allow you to complete GregTech Odyssey", "填满它就能通关GregTech Odyssey");
        addENCN("gtecore.tooltip.item.extremely_max_battery", "Fill it up within your lifetime", "有生之年将它填满");
        addENCN("gtecore.tooltip.item.insanely_max_battery", "Filling it up is just for fun", "填满也就图一乐");
        addENCN("gtecore.tooltip.item.mega_max_battery", "Fill up the battery for mechanical ascension", "填满电池 机械飞升");
        addENCN("gtecore.tooltip.item.tier_circuit", "%s Tier Circuit", "%s级电路");
        addENCN("gtecore.tooltip.item.suprachronal_circuit", "Running outside of known spacetime", "运行在已知时空之外");
        addENCN("gtecore.tooltip.item.magneto_resonatic_circuit", "Utilize the powerful magnetic field generated by magnetic resonance instruments to operate", "利用磁共振仪器产生的强大磁场来运行");
        addENCN("gtecore.tooltip.item.universal_circuit", "A universal circuit", "一个通用的电路");
        addENCN("gtecore.tooltip.item.craft_step", "Craft Step: %s", "合成步骤：%s");

        addENCN("item.gtecore.structure_detect.error.0", "Required at %s:", "需要在 %s:");
        addENCN("item.gtecore.structure_detect.error.1", "At %s:", "在 %s:");
        addENCN("item.gtecore.structure_detect.error.2", "[%s, %s, %s]-(%s)", "[%s, %s, %s]-(%s)");
        addENCN("item.gtecore.structure_detect.error.3", "Flipped Coordinates", "翻转的坐标");
        addENCN("item.gtecore.structure_detect.error.4", "Normal Coordinates", "正常坐标");
        addENCN("item.gtecore.structure_detect.tooltip.0", "Sneak right-click the main block to detect multiblock structure.", "潜行右键主方块以检测多方块结构");
        addENCN("item.gtecore.structure_detect.tooltip.1", "There may be lag when detecting large structures.", "检测大型结构时可能会有延迟");
        addENCN("item.gtecore.disc.data", "Disc data: %s", "光盘数据：%s");

        addENCN("item.gtecore.order.config", "Order Config", "订单配置");
    }
}
